### ISSUE TITLE
redesign courses cards

### ISSUE THREAD

**Issue by kelvinkamau** [kelvinkamau/vibranium-dark#19]
![image](https://user-images.githubusercontent.com/20049411/53906653-87bd2680-405c-11e9-8e10-53c62a39b849.png)

**Comment by pbrahmbhatt3** [comment]
can I work on this? @kelvinkamau

**Comment by kelvinkamau** [comment]
Sure thing..
Just push that PR when done..@pbrahmbhatt3

**Comment by pbrahmbhatt3** [comment]
@kelvinkamau I have also made pull request for 404 page. Also updated my code according to your review for teams card pull request. Can you have a look please?

**Comment by kelvinkamau** [comment]
Right on it. Sorry my schedule has been hella busy. @pbrahmbhatt3

**Comment by stellakaniaru** [comment]
Hey @pbrahmbhatt3 how far are you on this?

**Comment by kelvinkamau** [comment]
@stellakaniaru can you take over this?

**Comment by kelvinkamau** [comment]
![image](https://user-images.githubusercontent.com/20049411/68083502-1bd4cd00-fe3a-11e9-805a-20e503c80def.png)

![image](https://user-images.githubusercontent.com/20049411/68083467-cef0f680-fe39-11e9-8434-19d458cf8bb1.png)

Here is the live site [link](https://kelvinkamau.github.io/Vibranium-Dark-Mode/public/learn/index.html)
Hi @stellakaniaru 
Check on the following issues;
* Responsiveness of the cards on mobile devices
* Font size on desktop screens appears bigger than usual
* The height of the cards should be uniform
