### ISSUE TITLE
Redesign team cards to display all at once. #chore : (remove carousel)

### ISSUE THREAD

**Issue by kelvinkamau** [kelvinkamau/vibranium-dark#38]

**Comment by pbrahmbhatt3** [comment]
@kelvinkamau I have solved this issue and created a pull request. Can you please have a look at it? Thank you

**Comment by stellakaniaru** [comment]
Hey @pbrahmbhatt3 
The PR you submitted was dealing with issue #40. It has been reviewed.
This one looks at redesigning the team cards, as @kelvinkamau described above.
