### ISSUE TITLE
add a pre-loader

### ISSUE THREAD

**Issue by anniemburu** [kelvinkamau/vibranium-dark#4]

**Comment by pbrahmbhatt3** [comment]
can I work on this? @anniemburu

**Comment by stellakaniaru** [comment]
Hey @pbrahmbhatt3 , you definitely can. 

The pre-loader should be similar to the one on Github/Medium pages.

![pre-loader](https://user-images.githubusercontent.com/18654569/56462682-06351400-63d0-11e9-9b8d-71f88516698b.jpeg)
